/*!
 * Hyperion - Request
 * Copyright(c) 2012 Jake Luer <jake@qualiancy.com>
 * MIT Licensed
 */

/*!
 * External module dependencies
 */

var http = require('http')
  , uuid = require('pauli').uuid;

/*!
 * Extending http.IncomingMessage.prototype
 */

var req = exports = module.exports = {
  __proto__: http.IncomingMessage.prototype
};

/**
 * ### .id
 *
 * A unique id that is provided or generated for
 * a given request. Can either be generated by the
 * client and sent in as `header['x-request-id']`
 * or a uuid V4 will be generated as needed.
 *
 * // TODO: use uuid V1 (time based)
 *
 * @returns {String} request id
 * @name id
 * @api public
 */

Object.defineProperty(req, 'id',
  { get: function () {
      if (this._id) return this._id;
      this._id = this.headers['x-request-id'] || uuid();
      return this._id;
    }
});
